name: PrisonMain
main: org.Prison.Main.Main
version: 1.0
description: >
             Main plugin
commands:
  playermode:
    description: Staff Command
  reloadfiles:
    description: Staff Command
  setlocation:
    description: Staff Command
  tolocation:
    description: Staff Command 
  GiveVote:
    description: Staff Command
  save:
    description: Staff Command
  crystal:
    description: Staff Command
  exit:
    description: Staff Command
  silence:
    description: Staff Command 
  clearchat:
    description: Staff Command
  setletter:
    description: Staff Command
  setspeed:
    description: Staff Command
  setintellect:
    description: Staff Command
  booster:
    description: Staff Command
  removebooster:
    description: Staff Command
  boostertime:
    description: Check how much time is left on the current booster.
  updatelead:
    description: Staff Command
  sc:
    description: Staff Command
  test1:
    description: Staff Command 
  test2:
    description: Staff Command
  test3:
    description: Staff Command     
  givecorrupt:
    description: Staff Command                                           
                                        
